services:
  api:
    container_name: photo-grid-api
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  adminer:
    image: adminer
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
          
    ports:
      - 8080:8080
    
      
